"""Core SQLAlchemy persistence models for the Day 1 data foundation."""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Declarative model base used by Alembic metadata."""


class UUIDPrimaryKeyMixin:
    """PostgreSQL UUID primary key generated by the application."""

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """Timezone-aware creation and update timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )


class Space(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Top-level tenant/workspace boundary."""

    __tablename__ = "spaces"

    name: Mapped[str] = mapped_column(String(200), nullable=False)
    slug: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text)

    repositories: Mapped[list["Repository"]] = relationship(back_populates="space")
    sources: Mapped[list["Source"]] = relationship(back_populates="space")

    __table_args__ = (
        CheckConstraint("slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'", name="ck_spaces_slug_format"),
    )


class Repository(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """External source-code repository attached to a space."""

    __tablename__ = "repositories"

    space_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("spaces.id", ondelete="CASCADE"), nullable=False
    )
    provider: Mapped[str] = mapped_column(String(32), nullable=False, default="local")
    external_id: Mapped[str | None] = mapped_column(String(255))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str | None] = mapped_column(String(512))
    default_branch: Mapped[str | None] = mapped_column(String(255))
    web_url: Mapped[str | None] = mapped_column(Text)
    canonical_root_path: Mapped[str | None] = mapped_column(Text)
    authorization_status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="pending"
    )
    authorized_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    space: Mapped[Space] = relationship(back_populates="repositories")
    sources: Mapped[list["Source"]] = relationship(back_populates="repository")

    __table_args__ = (
        UniqueConstraint("space_id", "provider", "external_id", name="uq_repositories_external"),
        UniqueConstraint(
            "space_id", "canonical_root_path", name="uq_repositories_local_root"
        ),
        CheckConstraint("provider IN ('local', 'github')", name="ck_repositories_provider"),
        CheckConstraint(
            "authorization_status IN ('pending', 'authorized', 'revoked')",
            name="ck_repositories_authorization_status",
        ),
        CheckConstraint(
            "(provider = 'local' AND canonical_root_path IS NOT NULL "
            "AND external_id IS NULL AND web_url IS NULL) OR "
            "(provider = 'github' AND external_id IS NOT NULL "
            "AND full_name IS NOT NULL AND web_url IS NOT NULL "
            "AND canonical_root_path IS NULL)",
            name="ck_repositories_provider_fields",
        ),
        CheckConstraint(
            "authorization_status <> 'authorized' OR authorized_at IS NOT NULL",
            name="ck_repositories_authorized_at",
        ),
        CheckConstraint(
            "authorization_status <> 'revoked' OR revoked_at IS NOT NULL",
            name="ck_repositories_revoked_at",
        ),
        Index("ix_repositories_space_full_name", "space_id", "full_name"),
        Index(
            "ix_repositories_space_authorization",
            "space_id",
            "authorization_status",
        ),
    )


class Source(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Logical ingest source such as a repository, document, or URL."""

    __tablename__ = "sources"

    space_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("spaces.id", ondelete="CASCADE"), nullable=False
    )
    repository_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("repositories.id", ondelete="SET NULL")
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    uri: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="active")
    source_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict, server_default="{}"
    )

    space: Mapped[Space] = relationship(back_populates="sources")
    repository: Mapped[Repository | None] = relationship(back_populates="sources")
    versions: Mapped[list["SourceVersion"]] = relationship(back_populates="source")

    __table_args__ = (
        UniqueConstraint("space_id", "uri", name="uq_sources_space_uri"),
        CheckConstraint(
            "kind IN ('repository', 'document', 'url', 'notion')",
            name="ck_sources_kind",
        ),
        CheckConstraint("status IN ('active', 'disabled', 'error')", name="ck_sources_status"),
        Index("ix_sources_space_kind_status", "space_id", "kind", "status"),
    )


class SourceVersion(UUIDPrimaryKeyMixin, Base):
    """Immutable revision of a logical source."""

    __tablename__ = "source_versions"

    source_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sources.id", ondelete="CASCADE"), nullable=False
    )
    version_identifier: Mapped[str] = mapped_column(String(512), nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    storage_uri: Mapped[str | None] = mapped_column(Text)
    version_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict, server_default="{}"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    source: Mapped[Source] = relationship(back_populates="versions")
    index_jobs: Mapped[list["IndexJob"]] = relationship(back_populates="source_version")

    __table_args__ = (
        UniqueConstraint("source_id", "version_identifier", name="uq_source_versions_revision"),
        CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name="ck_source_versions_sha256"),
        Index("ix_source_versions_source_created", "source_id", created_at.desc()),
    )


class IndexJob(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Asynchronous indexing attempt for a source revision."""

    __tablename__ = "index_jobs"

    space_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("spaces.id", ondelete="CASCADE"), nullable=False
    )
    source_version_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("source_versions.id", ondelete="CASCADE"), nullable=False
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="pending")
    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    error_code: Mapped[str | None] = mapped_column(String(100))
    error_message: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    source_version: Mapped[SourceVersion] = relationship(back_populates="index_jobs")

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_index_jobs_status",
        ),
        CheckConstraint("attempt > 0", name="ck_index_jobs_attempt_positive"),
        CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name="ck_index_jobs_time_order",
        ),
        Index("ix_index_jobs_space_status_created", "space_id", "status", "created_at"),
        Index("ix_index_jobs_source_version", "source_version_id"),
    )


class QueryRun(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Auditable execution of a user query; provider credentials are never stored."""

    __tablename__ = "query_runs"

    space_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("spaces.id", ondelete="CASCADE"), nullable=False
    )
    request_id: Mapped[str] = mapped_column(String(128), nullable=False)
    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="pending")
    model_name: Mapped[str | None] = mapped_column(String(255))
    input_tokens: Mapped[int | None] = mapped_column(Integer)
    output_tokens: Mapped[int | None] = mapped_column(Integer)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error_code: Mapped[str | None] = mapped_column(String(100))

    events: Mapped[list["RunEvent"]] = relationship(back_populates="query_run")

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_query_runs_status",
        ),
        CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name="ck_query_runs_input_tokens",
        ),
        CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="ck_query_runs_output_tokens"
        ),
        CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name="ck_query_runs_time_order",
        ),
        Index("ix_query_runs_space_created", "space_id", "created_at"),
        Index("ix_query_runs_request_id", "request_id"),
    )


class RunEvent(UUIDPrimaryKeyMixin, Base):
    """Ordered append-only event emitted during a query run."""

    __tablename__ = "run_events"

    query_run_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("query_runs.id", ondelete="CASCADE"), nullable=False
    )
    sequence: Mapped[int] = mapped_column(Integer, nullable=False)
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict, server_default="{}"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    query_run: Mapped[QueryRun] = relationship(back_populates="events")

    __table_args__ = (
        UniqueConstraint("query_run_id", "sequence", name="uq_run_events_sequence"),
        CheckConstraint("sequence >= 0", name="ck_run_events_sequence"),
        Index("ix_run_events_run_created", "query_run_id", "created_at"),
    )


class AuditEvent(UUIDPrimaryKeyMixin, Base):
    """Append-only record of security and domain actions."""

    __tablename__ = "audit_events"

    space_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("spaces.id", ondelete="SET NULL")
    )
    actor_id: Mapped[str | None] = mapped_column(String(255))
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    resource_type: Mapped[str | None] = mapped_column(String(100))
    resource_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    request_id: Mapped[str | None] = mapped_column(String(128))
    correlation_id: Mapped[str | None] = mapped_column(String(128))
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict, server_default="{}"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("ix_audit_events_space_created", "space_id", "created_at"),
        Index("ix_audit_events_resource", "resource_type", "resource_id"),
        Index("ix_audit_events_request_id", "request_id"),
    )
